
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ManageStudent extends javax.swing.JFrame {

    /**
     * Creates new form ManageStudent
     */
    
    Student std = new Student();
    DefaultTableModel model;
    
    public ManageStudent() {
        initComponents();
        std.updateStudentTable(tablestd, ""); // at the start of popping the window, updates the student table using function from the Student class
        ButtonGroup bg = new ButtonGroup(); // make new button group the reason to make this is in the AddStudent class in a comment i wrote
        bg.add(jRadioButtonmale);
        bg.add(jRadioButtonfemale);
        model = (DefaultTableModel)tablestd.getModel(); // new student table model
        // just twinkling with the table's appearance
        tablestd.setRowHeight(30);
        tablestd.setShowGrid(true);
        tablestd.setGridColor(Color.BLUE);
        tablestd.setSelectionBackground(Color.BLACK);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtstdid = new javax.swing.JTextField();
        txtfirstname = new javax.swing.JTextField();
        txtlastname = new javax.swing.JTextField();
        txtphone = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtareaaddress = new javax.swing.JTextArea();
        jRadioButtonmale = new javax.swing.JRadioButton();
        jRadioButtonfemale = new javax.swing.JRadioButton();
        jDateChooserbirthdate = new com.toedter.calendar.JDateChooser();
        btnadd = new javax.swing.JButton();
        btnremove = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablestd = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        btnedit = new javax.swing.JButton();
        txtsearch = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));

        jPanel4.setBackground(new java.awt.Color(102, 255, 255));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Manage Students");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(323, 323, 323)
                .addComponent(jLabel1)
                .addContainerGap(350, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(22, 22, 22))
        );

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("First Name :");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Last Name :");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Gender :");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Birthdate :");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Phone :");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Address :");

        txtstdid.setEditable(false);
        txtstdid.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txtfirstname.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txtlastname.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txtphone.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtphone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtphoneKeyTyped(evt);
            }
        });

        txtareaaddress.setColumns(20);
        txtareaaddress.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtareaaddress.setRows(5);
        jScrollPane1.setViewportView(txtareaaddress);

        jRadioButtonmale.setText("Male");

        jRadioButtonfemale.setText("Female");

        jDateChooserbirthdate.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        btnadd.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnadd.setForeground(new java.awt.Color(0, 0, 0));
        btnadd.setText("Add");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btnremove.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnremove.setForeground(new java.awt.Color(0, 0, 0));
        btnremove.setText("Remove");
        btnremove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnremoveActionPerformed(evt);
            }
        });

        tablestd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "First Name", "Last Name", "Gender", "Birthdate", "Phone", "Address"
            }
        ));
        tablestd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablestdMouseClicked(evt);
            }
        });
        tablestd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tablestdKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tablestd);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Id :");

        btnedit.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnedit.setForeground(new java.awt.Color(0, 0, 0));
        btnedit.setText("Edit");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        txtsearch.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchActionPerformed(evt);
            }
        });
        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtsearchKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearchKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtsearchKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Search :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel8)
                .addGap(6, 6, 6)
                .addComponent(txtstdid, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(6, 6, 6)
                        .addComponent(txtfirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3)
                        .addGap(6, 6, 6)
                        .addComponent(txtlastname, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel4)
                        .addGap(6, 6, 6)
                        .addComponent(jRadioButtonmale)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonfemale))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel5)
                        .addGap(6, 6, 6)
                        .addComponent(jDateChooserbirthdate, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel6)
                        .addGap(6, 6, 6)
                        .addComponent(txtphone, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel7)
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnedit, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnremove, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel8))
                    .addComponent(txtstdid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel2))
                            .addComponent(txtfirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel3))
                            .addComponent(txtlastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel4))
                            .addComponent(jRadioButtonmale)
                            .addComponent(jRadioButtonfemale))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jDateChooserbirthdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel6))
                            .addComponent(txtphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnedit, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnremove, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtphoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtphoneKeyTyped
        // allow only numbers
        if(!Character.isDigit(evt.getKeyChar())){ // if the characters that we are typing are not digits they wont show up
            evt.consume(); // consumes the event so that it will not be processed
        }
    }//GEN-LAST:event_txtphoneKeyTyped
    
    public boolean verifyText(){
        
        // the same function in the addStudent class
        if(txtfirstname.getText().equals("") || txtlastname.getText().equals("") || 
            txtphone.getText().equals("") || txtareaaddress.getText().equals("") || 
            txtstdid.getText().equals("") || jDateChooserbirthdate.getDate() == null){
            
            JOptionPane.showMessageDialog(null, "Please fill in ALL of the given form");
            return false;
        }
        // can only choose a date higher than the current date in our world
        else if(jDateChooserbirthdate.getDate().compareTo(new Date()) > 0){
            
            JOptionPane.showMessageDialog(null, "Invalid date inputted");
            return false;
        }
        else{
            return true;
        }
    }
    
    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // if we click the add button on the screen, pops out a new AddStudent window too add students
        AddStudent addstd = new AddStudent();
        addstd.setVisible(true);
        addstd.pack();
        addstd.setLocationRelativeTo(null);
        addstd.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnaddActionPerformed

    private void btnremoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnremoveActionPerformed
        // removing a student means that all the scores that the student has will also be deleted
        // so i added a constraint to the score table to do this(done in the database) by executing a query in the below statement
        // basically what the below statement does is if i delete a student in the "student" table in the database, then the scores that the student has will also be deleted
        // what happens is that the score table which has student_id column will be altered or updated if any of the student id from the student table is deleted 
        // hence it also deletes a student id in the score table deleting a row of the score table as well
        // ALTER TABLE score  
        // add CONSTRAINT fk_score_student   
        // FOREIGN KEY (student_id) // student_id from child table which is the score table
        // REFERENCES student(id) // with the reference being the parent table with a given column, in this case its the student table since we are deleting a student and his/her id
        // on DELETE CASCADE
        // constraint -> foreign key + on deletee cascade
        
        if(txtstdid.getText().equals("")){
            // if there are no student id in the textfield, gives error message that no student has been selected to be deleted
            JOptionPane.showMessageDialog(null, "No Student Selected");
        }
        else{
            // if there is a student selected, 
            // store the student id selected in a variable
            int id = Integer.valueOf(txtstdid.getText());
            // delete a student with the id using function from the Student class
            std.insertUpdateDeleteStudent('d', id, null, null, null, null, null, null);
            // updates the table 
            std.updateStudentTable(tablestd, "");
            
            // making a new model table for me is to fix a bug i had
            // using my updatestudenttable function, it just + the newly updated table without deleting the unupdated table
            // so what i did is just to reset the table using a new model everytime we update a table 
            tablestd.setModel(new DefaultTableModel(null, new Object[]{"Id","First Name","Last Name","Gender","Birthdate","Phone","Address"}));
            std.updateStudentTable(tablestd, txtsearch.getText()); 
            
            // updates the student count on the main menu upon deleting a student
            Main.lblstdcount.setText("Students Count = " + Integer.toString(Functions.countData("student")));
            
            // blanks all the textfield in the form 
            txtfirstname.setText("");
            txtlastname.setText("");
            txtphone.setText("");
            txtareaaddress.setText("");
            jRadioButtonmale.setSelected(false);
            jRadioButtonfemale.setSelected(false);
            jDateChooserbirthdate.setDate(null);
        }
        
    }//GEN-LAST:event_btnremoveActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // store the texts typed by the user on the textfields to variables
        int id = Integer.valueOf(txtstdid.getText());
        String firstName = txtfirstname.getText();
        String lastName = txtlastname.getText();
        String phone = txtphone.getText();
        String address = txtareaaddress.getText();
        String gender = "Male";
        if(jRadioButtonfemale.isSelected()){
            gender = "Female";
        }
        
        if(verifyText()){
            
            // basically i did the same thing on the AddStudent class but the function for inserupdate dll i set it to update
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy--MM--dd");
            String birthdate = dateFormat.format(jDateChooserbirthdate.getDate());
            
            Student std = new Student();
            std.insertUpdateDeleteStudent('u', id, firstName, lastName, gender, birthdate, phone, address);

            ManageStudent.tablestd.setModel(new DefaultTableModel(null, new Object[]{"Id", "First Name", "Last Name", "Gender", "Birthdate", "Phone", "Address"}));
            std.updateStudentTable(ManageStudent.tablestd, "");
        }
    }//GEN-LAST:event_btneditActionPerformed
    
    int rowIndex;
    private void tablestdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablestdMouseClicked
        // what im doing here is if the user click on one of the rows on the table, then the textfields or forms are then filled with the data that just got clicked
        // so that they can edit the data that is in the table easily
        // store the index of the selected row in a variable
        rowIndex = tablestd.getSelectedRow();
        
        model = (DefaultTableModel)tablestd.getModel();
        
        jRadioButtonfemale.setSelected(false);
        jRadioButtonmale.setSelected(false);
        
        if(model.getValueAt(rowIndex, 3).toString().equals("Male")){
            // if tablemodel get value at (row index, column) which 3 is the gender column == male .....
            jRadioButtonmale.setSelected(true);
        }
        else{
            jRadioButtonfemale.setSelected(true);
        }
        
        // set the textfields with values from the student table 
        txtstdid.setText(model.getValueAt(rowIndex, 0).toString());
        txtfirstname.setText(model.getValueAt(rowIndex, 1).toString());
        txtlastname.setText(model.getValueAt(rowIndex, 2).toString());
        txtphone.setText(model.getValueAt(rowIndex, 5).toString());
        txtareaaddress.setText(model.getValueAt(rowIndex, 6).toString());
        
        Date birthdate;
        try {
            // this is how we get the date values from table to the text 
            birthdate = new SimpleDateFormat("yyyy-MM-dd").parse(model.getValueAt(rowIndex, 4).toString());
            jDateChooserbirthdate.setDate(birthdate);
        } catch (ParseException ex) {
            Logger.getLogger(ManageStudent.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tablestdMouseClicked

    private void txtsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearchActionPerformed
      
    }//GEN-LAST:event_txtsearchActionPerformed

    private void txtsearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyTyped
       
    }//GEN-LAST:event_txtsearchKeyTyped

    private void txtsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyReleased
        // using the updateStudentTable function i made a search feature in the window 
        // this happens when we type something in the search textfield
        tablestd.setModel(new DefaultTableModel(null, new Object[]{"Id","First Name","Last Name","Gender","Birthdate","Phone","Address"}));
        std.updateStudentTable(tablestd, txtsearch.getText()); 
    }//GEN-LAST:event_txtsearchKeyReleased

    private void txtsearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyPressed
        
    }//GEN-LAST:event_txtsearchKeyPressed

    private void tablestdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablestdKeyReleased
        
        // in the table(window) we can press the up down arrow keys when selecting the table to go up or down through the data
        // this is to make when we are going up or down through the data we also set the form or textfields according to the current data that we are on when we are going through them
        // its more clear in the video demonstration 
        if(evt.getKeyCode() == KeyEvent.VK_UP || evt.getKeyCode() == KeyEvent.VK_DOWN){
            
            // basically this is the same thing as the table mouse clicked
            // because how it works is the same
            rowIndex = tablestd.getSelectedRow();
            txtstdid.setText(model.getValueAt(rowIndex, 0).toString());
            txtfirstname.setText(model.getValueAt(rowIndex, 1).toString());
            txtlastname.setText(model.getValueAt(rowIndex, 2).toString());
            txtphone.setText(model.getValueAt(rowIndex, 5).toString());
            txtareaaddress.setText(model.getValueAt(rowIndex, 6).toString());
            
            if(model.getValueAt(rowIndex, 3).toString().equals("Male")){
                jRadioButtonmale.setSelected(true);
                jRadioButtonfemale.setSelected(false);
            }
            else{
                jRadioButtonfemale.setSelected(true);
                jRadioButtonmale.setSelected(false);
            }
            Date birthdate;
            try {
                birthdate = new SimpleDateFormat("yyyy-MM-dd").parse(model.getValueAt(rowIndex, 4).toString());
                jDateChooserbirthdate.setDate(birthdate);
            } catch (ParseException ex) {
                Logger.getLogger(ManageStudent.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_tablestdKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnremove;
    private com.toedter.calendar.JDateChooser jDateChooserbirthdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButtonfemale;
    private javax.swing.JRadioButton jRadioButtonmale;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable tablestd;
    private javax.swing.JTextArea txtareaaddress;
    private javax.swing.JTextField txtfirstname;
    private javax.swing.JTextField txtlastname;
    private javax.swing.JTextField txtphone;
    private javax.swing.JTextField txtsearch;
    private javax.swing.JTextField txtstdid;
    // End of variables declaration//GEN-END:variables
}
